
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/01_matmul.ipynb

import matplotlib as mpl
import torch
import math
import gzip
import pdb
import pickle
from pathlib import Path
from torch import tensor
import matplotlib.pyplot as plt
from fastai import datasets
from IPython.core.debugger import set_trace
from exp.nb_00 import *
import operator


def test(a, b, cmp, cname=None):
    if cname is None:
        cname = cmp.__name__
    assert cmp(a, b), f"{cname}:\n{a}\n{b}"


def test_eq(a, b): test(a, b, operator.eq, '==')


MNIST_URL = 'http://deeplearning.net/data/mnist/mnist.pkl'
pdb.set_trace()
def near(a, b): return torch.allclose(a, b, rtol=1e-3, atol=1e-5)
def test_near(a, b): test(a, b, near)
